### ISSUE TITLE
nova ne marche pas

### ISSUE THREAD

**Issue by EmiMestraud** [LeonLenclos/ateliers-chatbot#2]
Bonjour Léon, 

On a un pb ce matin, 
Nova ne marche pas et je ne comprends pas pourquoi ...

**Comment by LeonLenclos** [comment]
Salut, il y a des problème dans les rivescript qui font planter le Nova. Pour savoir quels sont ces problèmes je dois ouvrir la console javascript sur le navigateur (sur la page de Nova).

Chez moi c'est F12 pour ouvrir la console (Ça peut varier selon les navigateurs. Mais tu ne devrai pas avoir trop de mal à [la trouver](https://www.alsacreations.com/astuce/lire/1436-console-javascript.html))

![Capture d'écran de 2019-05-10 13-07-45](https://user-images.githubusercontent.com/19581526/57523290-e638a680-7324-11e9-8ea8-7db2b87ee58b.png)

La console me donne deux erreurs : 

    Response found before trigger at brain/salutations.rive line 1

et

    Syntax error: Piped arrays can't begin or end with a | at brain/insultes.rive line 8

Donc à chaque fois j'ai l'erreur qu'il a repéré (pas toujours clair mais souvent ça aide) et surtout, le fichier et la ligne où il a repéré l'erreur !!

Au final ça rend le debuggage assez simple. Je vais à [brain/salutations.rive ligne 1](https://github.com/LeonLenclos/ateliers-chatbot/blob/master/bots/gdr1/brain/salutations.rive#L1) et je vois que la ligne commence par un tiret (pour lui c'est donc une réponse, mais à quel déclencheur ??!!). Ensuite je vais à [brain/insultes.rive ligne 8](https://github.com/LeonLenclos/ateliers-chatbot/blob/master/bots/gdr1/brain/insultes.rive#L8) et je vois qu'en effet l'array fini par une barre verticale `|` ce qui est interdit.

À noter : 
- 99% des fois quand Nova ne marchera pas ce sera des erreurs de ce genre que tu pourra trouver en regardant la console
- Souvent les erreurs bloquent l'execution du code, donc il peut y avoir d'autres erreurs qui ne seront rencontrés qu'après avoir réglé celles là. (je veux dire : ne t’étonne pas si après avoir corrigé ces deux problèmes tu as deux nouveaux problèmes qui arrivent)
- Normalement le playground rivescript signale ces erreurs. Il faut que chacun test son code sur un playground avant de le mettre en ligne. 

Bon courage et salut à toute la team Nova de ma part !!!

**Comment by EmiMestraud** [comment]
Merci beaucoup,

super !!
je regarde ca de près
merci encore
