### ISSUE TITLE
impossible de mettre en ligne les corrections ... 

### ISSUE THREAD

**Issue by EmiMestraud** [LeonLenclos/ateliers-chatbot#3]
Léon, 

au secours, les élèves ont corrigé des petites choses et 
impossible de mettre en ligne les corrections ... 
est-ce normal ?

**Comment by LeonLenclos** [comment]
Peu d'indices pour te répondre. Non ce n'est pas normal. Si le bouton commit est grisé c'est souvent un problème de navigateur web pas compatible (vieux) si c'est le meme navigateur que tu utilise depuis le début c'est etrange.

**Comment by LeonLenclos** [comment]
Si tu me donne avant 12h les indications des mises à jour à faire je veux bien m'y coller. à toute

**Comment by EmiMestraud** [comment]
Merci beaucoup Léon

oui c'était ca, mon moteur de recherche
je n'ai pas changé ...
Ca y est je viens de le faire sur chrome donc OUF

je m'en occupe, prepare toi tranquillement
et désolée de t'avoir dérangé ,
merci encore

a tout à l'heure
